### PR TITLE
Support for user profiles

### PR DESCRIPTION
**Pull request by aleks**
I added links to every name and a tiny profile, so you can see which stories a user has submitted.

### CODE REVIEW

**Comment by aleks** [comment]
Preview

**Comment by 8bitpal** [comment]
Great job! Will deploy later. Thanks!

**Comment by aleks** [comment]
Mother of god, that was fast. Thanks! :)

**Comment by 8bitpal** [comment]
This randomly plays perfectly together with what I was doing. Just finished the user data model and was about to do what you did. Awesome!

**Comment by mattslight** [comment]
@aleks Thanks for the contribution!

**Pull request merged**
