### PR TITLE
Added code for issue requests #30 and #16

### PR DESCRIPTION
**Pull request by dsthode**
Adding request #30 for 'share url support' and #16 'redirect to destination other than the frontpage'

### CODE REVIEW

**Comment by dsthode** [comment]
(made a mess with my commits just look at the file changes :-D)

**Comment by dsthode** [comment]
Is anybody out there?

**Comment by 8bitpal** [comment]
Github didn't notify me of your commit for some reason. Thanks a lot! I'll have a look through and pull asap.

**Comment by 8bitpal** [comment]
Thanks a lot and sorry for the wait.
Will deploy with the next update.

**Pull request merged**
