### PR TITLE
Added more information to the RSS feed to use for a hackful (iOS) App

### PR DESCRIPTION
**Pull request by oemera**

### CODE REVIEW

**Comment by 8bitpal** [comment]
Thanks for your time, great addition!

**Comment by dsthode** [comment]
Just a question, has this change gone into production already? (I think it has not, because the link tag still shows the post URL, rather than the story link) If not, what's the updating schedule of the production code?

**Comment by 8bitpal** [comment]
Sorry, my other job has been consuming all my time. Deploying it now.

**Comment by dsthode** [comment]
Yay, thanks!

**Pull request merged**
